#!/bin/zsh -f

# Confirms which activeSilentMode value Little Snitch uses for each operation
# mode.
#
# Objective Development documents this preference only in passing, and only
# ever with the value 0. The workflow assumes 0 = Alert, 1 = Silent Allow,
# 2 = Silent Deny. If 1 and 2 were reversed, choosing "Silent Deny" would
# silently put the firewall into allow-everything while reporting success —
# the workflow's readback cannot catch that, because it compares against the
# same constant it wrote.
#
# This script only READS. You change the mode yourself, in Little Snitch's own
# interface, and it reports what the preference says.
#
#   sudo ./scripts/verify-modes.zsh

set -u

typeset -gr SCRIPT_DIR="${0:A:h}"
typeset -gr ROOT_DIR="${SCRIPT_DIR:h}"
typeset -gr CLI="/Applications/Little Snitch.app/Contents/Components/littlesnitch"
typeset -gr REQUIREMENT='=identifier "littlesnitch" and anchor apple generic and certificate leaf[subject.OU] = "MLZF7K7B5R"'
typeset -gr REPORT="$ROOT_DIR/docs/VERIFIED-MODES.md"

abort() {
  /usr/bin/printf 'error: %s\n' "$1" >&2
  exit 1
}

(( EUID == 0 )) || abort "run this with sudo — every littlesnitch subcommand requires root, including reads."
[[ -x "$CLI" ]] || abort "Little Snitch 6 was not found in /Applications."
/usr/bin/codesign --verify --strict -R "$REQUIREMENT" "$CLI" >/dev/null 2>&1 || \
  abort "the littlesnitch executable failed signature verification."

version_output=$("$CLI" --version 2>/dev/null) || abort "could not run littlesnitch --version."
version="${version_output#Version }"

read_mode() {
  local value
  value=$("$CLI" read-preference activeSilentMode 2>&1) || return 1
  [[ "$value" == <-> ]] || return 1
  print -r -- "$value"
}

probe=$(read_mode) || abort "could not read activeSilentMode. Enable Little Snitch → Settings → Security → Allow access via Terminal, then try again."

/usr/bin/printf '\nLittle Snitch %s — operation mode mapping check\n' "$version"
/usr/bin/printf 'Nothing is written. Change each mode in Little Snitch, then press Return here.\n\n'

typeset -A observed
typeset -a order
order=("Alert Mode" "Silent Mode - Allow" "Silent Mode - Deny")

for label in "${order[@]}"; do
  /usr/bin/printf 'Set Little Snitch to \033[1m%s\033[0m (menu bar icon → Operation Mode), then press Return… ' "$label"
  read -r _ || true
  value=$(read_mode) || abort "could not read activeSilentMode."
  observed[$label]="$value"
  /usr/bin/printf '  activeSilentMode = %s\n\n' "$value"
done

/usr/bin/printf '\nResult\n'
status=0
typeset -A expected
expected=("Alert Mode" 0 "Silent Mode - Allow" 1 "Silent Mode - Deny" 2)
typeset -a seen
seen=()
for label in "${order[@]}"; do
  value="${observed[$label]}"
  if [[ "$value" == "${expected[$label]}" ]]; then
    /usr/bin/printf '  %-22s %s  matches the workflow\n' "$label" "$value"
  else
    /usr/bin/printf '  %-22s %s  DOES NOT MATCH (workflow assumes %s)\n' "$label" "$value" "${expected[$label]}"
    status=1
  fi
  seen+=("$value")
done

unique=$(/usr/bin/printf '%s\n' "${seen[@]}" | /usr/bin/sort -u | /usr/bin/wc -l | /usr/bin/tr -d ' ')
if [[ "$unique" != "3" ]]; then
  /usr/bin/printf '\n  Only %s distinct values were observed. The mode probably did not change\n  between prompts — rerun and confirm each change in Little Snitch first.\n' "$unique"
  status=1
fi

/bin/mkdir -p "$ROOT_DIR/docs"
{
  /usr/bin/printf '# Verified operation-mode values\n\n'
  /usr/bin/printf 'Generated by `scripts/verify-modes.zsh`. Read-only: the script never writes a preference.\n\n'
  /usr/bin/printf -- '- Little Snitch: %s\n' "$version"
  /usr/bin/printf -- '- macOS: %s (%s)\n' "$(/usr/bin/sw_vers -productVersion)" "$(/usr/bin/uname -m)"
  /usr/bin/printf -- '- Checked: %s\n\n' "$(/bin/date -u '+%Y-%m-%d')"
  /usr/bin/printf '| Little Snitch operation mode | `activeSilentMode` | Workflow action |\n'
  /usr/bin/printf '| --- | --- | --- |\n'
  /usr/bin/printf '| Alert Mode | `%s` | `mode.alert` |\n' "${observed[Alert Mode]}"
  /usr/bin/printf '| Silent Mode - Allow | `%s` | `mode.silent-allow` |\n' "${observed[Silent Mode - Allow]}"
  /usr/bin/printf '| Silent Mode - Deny | `%s` | `mode.silent-deny` |\n\n' "${observed[Silent Mode - Deny]}"
  if (( status == 0 )); then
    /usr/bin/printf 'The values match the mapping in `workflow/bin/authorize.applescript`.\n'
  else
    /usr/bin/printf '**Mismatch — do not release.** Update the mapping in `workflow/bin/authorize.applescript`\nand `workflow/bin/action`, then rerun this script.\n'
  fi
} > "$REPORT"

/usr/bin/printf '\nWrote %s\n' "${REPORT#$ROOT_DIR/}"
if (( status != 0 )); then
  /usr/bin/printf '\nDo not tag a release until this reports a match.\n'
fi
exit $status
