#!/bin/zsh -f

# Confirms which activeSilentMode value Little Snitch uses for each operation
# mode.
#
# Objective Development documents this preference only in passing, and only
# ever with the value 0. The workflow assumes 0 = Alert, 1 = Silent Allow,
# 2 = Silent Deny. If 1 and 2 were reversed, choosing "Silent Deny" would
# silently put the firewall into allow-everything while reporting success —
# the workflow's readback cannot catch that, because it compares against the
# same constant it wrote.
#
# This script only READS. You change the mode yourself, in Little Snitch's own
# interface, and it reports what the preference says.
#
#   sudo ./scripts/verify-modes.zsh
#
# --self-test <dir> exercises the comparison and report writing with fixed
# values, without root, Little Snitch, or the interactive prompts. The
# reporting code is otherwise reachable only after three prompts and a
# password, which is a poor place for a bug to hide.

set -u

typeset -gr SCRIPT_DIR="${0:A:h}"
typeset -gr ROOT_DIR="${SCRIPT_DIR:h}"
typeset -gr CLI="/Applications/Little Snitch.app/Contents/Components/littlesnitch"
typeset -gr REQUIREMENT='=identifier "littlesnitch" and anchor apple generic and certificate leaf[subject.OU] = "MLZF7K7B5R"'

typeset -gr ALERT_LABEL="Alert Mode"
typeset -gr ALLOW_LABEL="Silent Mode - Allow"
typeset -gr DENY_LABEL="Silent Mode - Deny"

abort() {
  /usr/bin/printf 'error: %s\n' "$1" >&2
  exit 1
}

# Compares the observed values against the workflow's mapping, prints the
# result, and writes the report. Returns non-zero on any mismatch.
render_result() {
  local alert="$1" allow="$2" deny="$3" report="$4" version="$5" platform="$6" today="$7"
  local -i mismatches=0
  local -a observed
  observed=("$alert" "$allow" "$deny")

  /usr/bin/printf '\nResult\n'
  local -i position=1
  local label expected value
  for label in "$ALERT_LABEL" "$ALLOW_LABEL" "$DENY_LABEL"; do
    expected=$(( position - 1 ))
    value="${observed[$position]}"
    if [[ "$value" == "$expected" ]]; then
      /usr/bin/printf '  %-22s %s  matches the workflow\n' "$label" "$value"
    else
      /usr/bin/printf '  %-22s %s  DOES NOT MATCH (workflow assumes %s)\n' "$label" "$value" "$expected"
      mismatches=$(( mismatches + 1 ))
    fi
    position=$(( position + 1 ))
  done

  local distinct
  distinct=$(/usr/bin/printf '%s\n' "${observed[@]}" | /usr/bin/sort -u | /usr/bin/wc -l | /usr/bin/tr -d ' ')
  if [[ "$distinct" != "3" ]]; then
    /usr/bin/printf '\n  Only %s distinct values were observed. The mode probably did not change\n' "$distinct"
    /usr/bin/printf '  between prompts — rerun and confirm each change in Little Snitch first.\n'
    mismatches=$(( mismatches + 1 ))
  fi

  /bin/mkdir -p "${report:h}"
  {
    /usr/bin/printf '# Verified operation-mode values\n\n'
    /usr/bin/printf 'Generated by `scripts/verify-modes.zsh`. Read-only: the script never writes a\n'
    /usr/bin/printf 'Little Snitch preference. The mode was changed by hand in Little Snitch between\n'
    /usr/bin/printf 'readings.\n\n'
    /usr/bin/printf -- '- Little Snitch: %s\n' "$version"
    /usr/bin/printf -- '- macOS: %s\n' "$platform"
    /usr/bin/printf -- '- Checked: %s\n\n' "$today"
    /usr/bin/printf '| Little Snitch operation mode | `activeSilentMode` | Workflow action |\n'
    /usr/bin/printf '| --- | --- | --- |\n'
    /usr/bin/printf '| %s | `%s` | `mode.alert` |\n' "$ALERT_LABEL" "$alert"
    /usr/bin/printf '| %s | `%s` | `mode.silent-allow` |\n' "$ALLOW_LABEL" "$allow"
    /usr/bin/printf '| %s | `%s` | `mode.silent-deny` |\n\n' "$DENY_LABEL" "$deny"
    if (( mismatches == 0 )); then
      /usr/bin/printf 'These values match the mapping in `workflow/bin/authorize.applescript`.\n'
    else
      /usr/bin/printf '**Mismatch — do not release.** Update the mapping in\n'
      /usr/bin/printf '`workflow/bin/authorize.applescript` and `workflow/bin/action`, then rerun.\n'
    fi
  } > "$report"

  /usr/bin/printf '\nWrote %s\n' "$report"
  (( mismatches == 0 ))
}

if [[ "${1:-}" == "--self-test" ]]; then
  self_test_dir="${2:-}"
  [[ -n "$self_test_dir" ]] || abort "--self-test needs a directory"
  /bin/mkdir -p "$self_test_dir"

  render_result 0 1 2 "$self_test_dir/match.md" "6.4.1" "26.0 (arm64)" "1980-01-01" >/dev/null || \
    abort "self-test: the expected mapping was reported as a mismatch"
  /usr/bin/grep -q 'match the mapping' "$self_test_dir/match.md" || \
    abort "self-test: the matching report was not written correctly"

  if render_result 0 2 1 "$self_test_dir/swapped.md" "6.4.1" "26.0 (arm64)" "1980-01-01" >/dev/null; then
    abort "self-test: a swapped mapping was reported as a match"
  fi
  /usr/bin/grep -q 'do not release' "$self_test_dir/swapped.md" || \
    abort "self-test: the mismatch report was not written correctly"

  if render_result 0 0 0 "$self_test_dir/stuck.md" "6.4.1" "26.0 (arm64)" "1980-01-01" >/dev/null; then
    abort "self-test: an unchanged mode was reported as a match"
  fi

  /usr/bin/printf 'verify-modes self-test passed\n'
  exit 0
fi

(( EUID == 0 )) || abort "run this with sudo — every littlesnitch subcommand requires root, including reads."
[[ -x "$CLI" ]] || abort "Little Snitch 6 was not found in /Applications."
/usr/bin/codesign --verify --strict -R "$REQUIREMENT" "$CLI" >/dev/null 2>&1 || \
  abort "the littlesnitch executable failed signature verification."

version_output=$("$CLI" --version 2>/dev/null) || abort "could not run littlesnitch --version."
version="${version_output#Version }"

read_mode() {
  local value
  value=$("$CLI" read-preference activeSilentMode 2>&1) || return 1
  [[ "$value" == <-> ]] || return 1
  print -r -- "$value"
}

read_mode >/dev/null || \
  abort "could not read activeSilentMode. Enable Little Snitch → Settings → Security → Allow access via Terminal, then try again."

/usr/bin/printf '\nLittle Snitch %s — operation mode mapping check\n' "$version"
/usr/bin/printf 'Nothing is written. Change each mode in Little Snitch, then press Return here.\n\n'

typeset -a readings
readings=()
for label in "$ALERT_LABEL" "$ALLOW_LABEL" "$DENY_LABEL"; do
  /usr/bin/printf 'Set Little Snitch to \033[1m%s\033[0m (menu bar icon → Operation Mode), then press Return… ' "$label"
  read -r _ || true
  value=$(read_mode) || abort "could not read activeSilentMode."
  readings+=("$value")
  /usr/bin/printf '  activeSilentMode = %s\n\n' "$value"
done

render_result "${readings[1]}" "${readings[2]}" "${readings[3]}" \
  "$ROOT_DIR/docs/VERIFIED-MODES.md" \
  "$version" \
  "$(/usr/bin/sw_vers -productVersion) ($(/usr/bin/uname -m))" \
  "$(/bin/date -u '+%Y-%m-%d')" || {
  /usr/bin/printf '\nDo not tag a release until this reports a match.\n'
  exit 1
}
exit 0
